### ISSUE TITLE
Repo search limited to visible repos

### ISSUE THREAD

**Issue by dtom90** [IBM/ibm.github.io#107]
Entering text in the search field only filters the visible repos, not all repos. In order to return the correct result, user must select "Show More" and then do the search, which is not ideal process.

**Comment by ckadner** [comment]
I agree with @dtom90 

From what I can tell, the search happens client-side via JavaScript, so it seems reasonable that the search scope is limited to those repositories which have already been loaded from GitHub (i.e. the first 20).

However, when I look at my browser console, I see a lot of `GET` requests to  api.github.com (i.e. https://api.github.com/orgs/QISKit/repos?per_page=1000&client_id=***&client_secret=***). So it appears that the repository data is available (after some delay). It's just not displayed yet, which should not be a limiting factor for the search scope.

**Comment by Nitair** [comment]
I agree with you. I've just changed the given code to make this site faster (but not better). He does fetch all repos (you can see that on the page)

> REPOS: 20 SHOWN. CLICK 'SHOW MORE' TO SEE OTHER 1194 REPOS

But on this point I just removed the visual part and limited that on 20, but all data is still given. I was thinking about implementing AJAX for the search. What do you think about implementing AJAX?

**Comment by christo4ferris** [comment]
The UX is being reworked, closing this. Thanks.
