### ISSUE TITLE
Search bar layout broken

### ISSUE THREAD

**Issue by Pettalves** [IBM/ibm.github.io#110]
The `show more` and `show less` buttons have different sizes and the search input box doesn't expand all the way to the end (right) of the content width.

Overall it look broken because the elements don't align.

**Comment by Pettalves** [comment]
@stevemart I updated the description here ;)

**Comment by Pettalves** [comment]
Before:

![image](https://user-images.githubusercontent.com/12205157/34736426-04b5f512-f55a-11e7-9625-5bc724f6bfd6.png)

After:

![image](https://user-images.githubusercontent.com/12205157/34736452-1f454d2e-f55a-11e7-8026-c07ccc5fc976.png)

**Comment by stevemart** [comment]
@Pettalves ah yeah, i see it now when i resize
