### ISSUE TITLE
Please add https://github.com/IBM/API4JSON to search results

### ISSUE THREAD

**Issue by wnm3** [IBM/ibm.github.io#124]
We recently added our Open Source project to the IBM Code Open Source github, but it isn't found when searching. It is public. There is some redirection from its original home (https://github.com/wnm3/API4JSON) but it seems this has not caused any problem for other services like git...

Thank you in advance for your help.

**Comment by stevemart** [comment]
@wnm3 you can update https://github.com/IBM/ibm.github.io/blob/master/orgs.js with the repo and org name, i've been hesitant to add the entire IBM org there, but we can add yours as a one-off. do you feel comfortable updating the file?

**Comment by wnm3** [comment]
It appears to be there now (thank you for adding it), but I guess there is a delay for the website to read the change. Checking here:

 
Best Regards, Nat
 
Nathaniel Mills
Senior Technical Staff Member - Project Lead / Chief Architect WILD Conversation Workflow Orchestration Project
Phone: 1-860-812-5089 (m)
E-mail: wnm3@us.ibm.com
 
 
----- Original message -----From: Steve Martinelli <notifications@github.com>To: "IBM/ibm.github.io" <ibm.github.io@noreply.github.com>Cc: Nathaniel Mills <wnm3@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [IBM/ibm.github.io] Please add https://github.com/IBM/API4JSON to search results (#124)Date: Wed, Jun 6, 2018 3:23 PM 
@wnm3 you can update https://github.com/IBM/ibm.github.io/blob/master/orgs.js with the repo and org name, i've been hesitant to add the entire IBM org there, but we can add yours as a one-off. do you feel comfortable updating the file?
