### ISSUE TITLE
Remove IBM affiliation

### ISSUE THREAD

**Issue by 2uasimojo** [IBM/ibm.github.io#139]
Howdy. I no longer work for IBM. Can the company affiliation be removed from my github profile? Is that something I do or something you do?

**Comment by stevemart** [comment]
Hi @2uasimojo you can do this yourself or I can remove you. I'll post the steps here should any others have a similar question.

You can go to https://github.com/settings/organizations to see orgs that you're a member of, and simply click `Leave`. Here's my org list for example:

<img width="837" alt="screen shot 2019-01-11 at 11 53 11 am" src="https://user-images.githubusercontent.com/4118756/51047902-a2f94180-1597-11e9-9d42-e6340b273496.png">

**Comment by 2uasimojo** [comment]
Thanks Steve, done.
