### ISSUE TITLE
Apply to add me to the IBM org

### ISSUE THREAD

**Issue by mayijieibm** [IBM/ibm.github.io#140]
Hi,

I need to upload some scripts to the repo IBM/solution-test-samples and the repo owner said he couldn't fine me in the org people tab. Could you help to send me the invitation to join in the org so that the repo owner could later add me in. Thank you.

id: mayijieibm
email add: mayijie@cn.ibm.com

**Comment by stevemart** [comment]
@mayijieibm i invited you to the org, check your email.

**Comment by mayijieibm** [comment]
Hi Steve,

Thank you very much for the rapid reply :-)
