### ISSUE TITLE
add link to http://ibm.github.io to various places

### ISSUE THREAD

**Issue by pmuellr** [IBM/ibm.github.io#3]
Should be in the descriptions for both this project and the org.

Should also be in the README.md for this project.

If folks wander to this this project, somehow, we should give them a link to the actual github.io page - but I don't see that anywhere.

**Comment by christo4ferris** [comment]
I think this has been resolved  - but thanks, Pat! (I was expecting others to more closely monitor the issues and PRs, so didn't see this until now).
