### ISSUE TITLE
greetings and org questions

### ISSUE THREAD

**Issue by vmorris** [IBM/ibm.github.io#47]
@IBM/oss-ibmers 

I couldn't find a better place to leave this message, so here goes.. What's the intended use of this github group? It looks like I have the capability to fork projects as "IBM" but I'm not keen on doing that myself. I've sent in a pull request to one of the two projects in this org, but it's been ignored. Plus there are a hundred other IBM organizations on github; if this is the official org, are we going to be forking a bunch to here, or is this just for show?

**Comment by ScarletTanager** [comment]
I don't see a huge reason to be shy about forking here, personally - doing so implies nothing more than, "I'm an IBMer and looking into a potential contribution to project <name>."  And once a fork is created, I assume others can/will create branches as necessary, so it shouldn't appear as something proprietary, etc.

Having said that, yes, there are other IBM orgs (I work on forks in cfibmers, e.g.), so IMHO your question is a valid one.  When I saw the email (I think from @christo4ferris ) adding me, I assumed that the main purpose of the group was to show the critical mass of IBM OSS contributors in a one-stop-shopping manner.

**Comment by christo4ferris** [comment]
hmmm... no one should be able to fork into here but owners... let me check permissions again.

The intention of this team (oss-ibmers) is to show the flag. You are all IBMers engaged in open source and we have a mandate from Ginni to improve IBM's perceived presence on GitHub. IBM does a LOT in open source, but as we are a large and diverse company, our efforts are scattered across many orgs on GitHub. By inviting IBMers to this team, and having them make their membership public (ahem), we can at least demonstrate how many we are (more are being added every week).

As for repos here, we are vetting those through our internal open source processes. 

@IBM/oss-ibmers

**Comment by christo4ferris** [comment]
also, too... no one but an owner (such as myself) should have permissions to fork to this org... I just tested to be sure and while the org shows up, you cannot select it for a destination of a fork.

**Comment by vmorris** [comment]
@christo4ferris Yep, you're correct. I saw the IBM org show up in my list when forking a project, but it doesn't let me select it. Thanks for the clarifications.
