### ISSUE TITLE
Cull StrongLoop repos

### ISSUE THREAD

**Issue by crandmck** [IBM/ibm.github.io#49]
Some of the 129 StrongLoop repos recently added (in #48) are outdated, un-maintained, or deprecated.  The StrongLoop team needs to review them to ensure only appropriate repos are listed in http://ibm.github.io/.

@rmg @sam-github @chandadharap @raymondfeng @ritch 

I _assume_ that we should not include repos that are very outdated or deprecated, but I don't know if there are any specific criteria for inclusion.  For example  are these appropriate:
- Example apps, primarily for LoopBack.  
- Repos used exclusively for testing.
- Repos that are essentially abandoned.

@christo4ferris Please advise.

I went through the repos recently added, and here are ones I'm fairly sure are deprecated/outdated:
- strongloop/bacn
- strongloop/generator-bacn
- strongloop/supercluster
- strongloop/zone
- strongloop/gill
- strongloop/icars-client
- strongloop/profiler-demo-app
- strongloop/express-zone

These are the repos I'm not sure about:
- strongloop/strong-cluster-socket.io-store
- strongloop/strong-store-cluster
- strongloop/strong-cluster-connect-store
- strongloop/strong-cluster-tls-store
- strongloop/node-who
- strongloop/strong-caching-http-client
- strongloop/strong-data-uri
- strongloop/loopback-testing
- strongloop/loopback-policy
- strongloop/gateway-workspace
- strongloop/strong-mesh-demo
- strongloop/strong-db-watcher
- strongloop/ephemeral-npm
- strongloop/pm-load-test

**Comment by richardpringle** [comment]
loopback-connector-remote is still maintained

**Comment by crandmck** [comment]
Thanks, I'll edit the list above based on comments. (That one was an oversight, I know it's used! :-) )
thx @richardpringle

**Comment by sam-github** [comment]
@crandmck if this was a PR I could comment, I can't even edit, must not be enough of a member.

strong-cluster-control , strong-registry, strong-tunnel in above list are all actively maintained

**Comment by christo4ferris** [comment]
@crandmck not up to me... if you choose to prune legacy repos, that is fine with me. Ideally what we have here is current. I filter out forks, but aside from ensuring that it "belongs" to IBM, I think it is fair game.

Frankly, what SL might want to do is clean up the org and have that hold current and open source repos, and create separate org for deprecated stuff and another for proprietary work. I'll leave that to you guys.

**Comment by crandmck** [comment]
Thanks @sam-github I will open a PR and you can review / comment again if you wish.
I'll remove the ones you mention from the list.

Thx @christo4ferris Your suggestion makes sense, and I will pass it on...for but the moment, I'll just work on pruning repos from the list.

**Comment by rmg** [comment]
As I said in https://github.com/IBM/ibm.github.io/pull/51#issuecomment-219804778:
> Personally, I don't think any of them should be removed unless the repos themselves have been deleted. I consider ibm.github.io an inventory of open source repositories, not a tool for promoting specific repositories.

**Comment by sam-github** [comment]
Its hard for me to have any comment since ibm.github.io is so broken it just freezes in my browser. Oh wait, just took a couple minutes to load.

Anyhow, shrug, whether we clean it up depends on its purpose. Not clear to me.

**Comment by crandmck** [comment]
Fixed by https://github.com/IBM/ibm.github.io/pull/51
