### ISSUE TITLE
Site loads funny in Chrome

### ISSUE THREAD

**Issue by schacon** [IBM/ibm.github.io#5]
This is what I'm seeing in Chrome 38.0.2125.122 on Mac if I load the site over https:

![ibm github-1](https://cloud.githubusercontent.com/assets/70/5046491/9395d5f8-6c0b-11e4-94ed-cc6545059c86.png)

It looks fine in Safari but in Chrome since it looks like the stylesheets are hardcoded to non-https URLs you're getting a failure of some of the css to load.

**Comment by ramesh10757** [comment]
Using the customized bootstrap.css fixes the issue more or less, is it required to use the http://getbootstrap.com/examples/jumbotron/jumbotron.css?

**Comment by kineticsquid** [comment]
Sorry for the delay. I noticed the behavior in the screen cap above once or twice a while ago, but not recently and I can't seem to recreate now. Still an issue?

**Comment by schacon** [comment]
Nope, looks good now. Thanks!

**Comment by kineticsquid** [comment]
Thanks
