### ISSUE TITLE
Main page has severe performance issues when loading repos

### ISSUE THREAD

**Issue by camporter** [IBM/ibm.github.io#53]
Viewing ibm.github.io results in a complete slowdown of Firefox 46.0.1 and Chrome 51.0.2704.54 on OSX 10.11.5. Loading the repos on the page seems to be causing lots of performance issues.

**Comment by jrfnl** [comment]
Not just that, it actually completely freezes the browser when using Palemoon.... Argh.. crash& burn

**Comment by christo4ferris** [comment]
I've reverted the changes that enumerated all of the strongloop repos individually which is what was causing the performance issues. Working on a site redesign soon.

**Comment by srl295** [comment]
In #44 I added a progress bar - otherwise, you don't know if the page has finished loading or is just stuck. #52 reverted this because the page slowed to a crawl (sorry about that). Re investigate it?

**Comment by christo4ferris** [comment]
I reverted because it caused severe performance degradation. I haven't had time to investigate. I would welcome any help in tracking that down, though!

**Comment by ajdlinux** [comment]
I still find this page is very slow on a modern Firefox (56.0 on Linux).

(Being mindful that I have not at all been involved in the development of this site - but it occurs to me that the repository information doesn't really need to be in real time, and could potentially be generated statically and updated by a bot every so often to avoid all the API calls.)
