### ISSUE TITLE
Analytics errors

### ISSUE THREAD

**Issue by srl295** [IBM/ibm.github.io#59]
the analytics such as 

```
    // Google Analytics Event Tracking
    $('body').on('click', 'a[data-analytics-category][data-analytics-action]', function(e){
```

… don't get installed unless you first search for something. This seems odd. It's because the analytics handlers are installed inside of the keyup handler `$('#search').keyup(function() {`.

In  b162e4bc3e4413bcf3824844abc123d8bb5616a3 I tried to fix this. Perhaps that was part of the slowdown.

**Comment by christo4ferris** [comment]
this has been resolved, thanks
