### ISSUE TITLE
Hardcoded client_id and secret

### ISSUE THREAD

**Issue by snufkin** [IBM/ibm.github.io#62]
Does it not pose security risks to have the client ID and the client_secret hardcoded in the requests?

**Comment by Nitair** [comment]
`// These client tokens are for a dummy app, and there is no user specific
                // information that we get, so all in all, pretty safe to expose this here.
                var uri = "https://api.github.com/" + orgs.type + "s/" + org + reposcmd +
                    "?per_page=1000" +
                    "&client_id=1bafa09b6086eec7afb4" +
                    "&client_secret=7e6422a0a2e24f0d0ecb7521a63990b5758c9cc8";
`

**Comment by christo4ferris** [comment]
this was resolved. Thanks
