### ISSUE TITLE
membership visibility

### ISSUE THREAD

**Issue by christo4ferris** [IBM/ibm.github.io#69]
@IBM/oss-ibmers 

Note that the default visibility setting is "Private" for all GitHub orgs. That means, when you accept an invitation to a GH org or team, your membership is hidden from all but the other members of the org.

I am asking that all of you please review your membership setting. To do this, open https://github.com/orgs/IBM/people in your browser and enter your GHid in the search field ("Find a member"). There's a radio button that should say "Public" in the third column. If it instead says "Private" please change it to "Public".

Thanks!

Chris

**Comment by gibfahn** [comment]
Pictorial example:

![image](https://user-images.githubusercontent.com/15943089/27180873-21571df8-51cd-11e7-929b-c4b1a7f740ab.png)

**Comment by sasa-tomic** [comment]
Why is this not done automatically? Github has a nice API afaik...

**Comment by Tyrael** [comment]
because if it would be possible people would invite you into organizations with nasty names and making your affiliation public.

**Comment by gibfahn** [comment]
>because if it would be possible people would invite you into organizations with nasty names and making your affiliation public.

But you have to accept the invitation before it shows up.

**Comment by sasa-tomic** [comment]
@Tyrael This is obviously not an issue with the IBM org. The question is rather: "can we make the membership in the IBM org automatically public?"
I had no idea that this has to be done manually, and I bet most people don't know that either.

**Comment by stevemart** [comment]
@sasa-tomic unfortunately it cannot be done automatically. Even as an admin for an org, I cannot set an individual's membership visibility manually through the UI. See the note in the API docs, too: https://developer.github.com/v3/orgs/members/#publicize-a-users-membership 

<img width="676" alt="screen shot 2018-01-22 at 10 55 18 am" src="https://user-images.githubusercontent.com/4118756/35230132-329cac24-ff63-11e7-9470-51ae334587e9.png">

**Comment by christo4ferris** [comment]
@Tyrael maybe we could convince @rmg to update the mapper? Actually, more challenging than it seems. It would also need permissions to invite people to the org, and then accept on their behalf and change their visibility.

That aside, it would help if people just paid attention;-)

**Comment by boneskull** [comment]
@christo4ferris I created an issue for this in the mapper repo, fwiw

**Comment by fjeremic** [comment]
I've linked my internal GitHub Enterprise account to my public one (this one). How do I get an invite to the @IBM org on GitHub?

**Comment by stevemart** [comment]
@fjeremic i just sent you an invite.

**Comment by MHBauer** [comment]
how do you link account from enterprise to public?

**Comment by fjeremic** [comment]
> how do you link account from enterprise to public?

Forwarded you an email with the appropriate link.

**Comment by stevemart** [comment]
@MHBauer and anyone else on the thread, the mapper is here: the https://github-user.w3ibm.mybluemix.net/

**Comment by RicardoToledo** [comment]
How do I get the invitation to join IBM's organization after linking my IBM account with my personal one?

**Comment by stevemart** [comment]
@RicardoToledo invite sent!

**Comment by christo4ferris** [comment]
I usually run the batch load once a week - you should see it shortly
